### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by sibelius** [react-native-dojo/BloodDonationDojo#4]
Which database design do we need for this app?
Which models, and with which fields?

We are going to use MongoDB (NoSQL), in Node.
[Mongoose](https://github.com/Automattic/mongoose) is a good option for this.

You should provide js files containing **Mongoose** Schemas describing the models and their relationships.

You have 3 days (due date 16/02/2016)

Make a PR to this repo, adding the files to **design/models** folder

Example of folder structure for this PR:

```
design
  models
    user.js
    hospitals.js
    ...
    another_model.js
```

**Comment by sibelius** [comment]
@lucasbsilva and @tzdesing will work together on this issue

**Comment by keuller** [comment]
Which server will be hosted the database ? I would like suggest Firebase, because we can create a free account. React has a good integration API for Firebase as well.

**Comment by lucasbento** [comment]
@keuller never tried Firebase but I guess we can use it as long as it's easy to export our data if we need to scale later.
